### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by tvzeller** [Redfielder/NeverEver#1]
## TODOs BEFORE PRESENTATION
- [x] git pull, makemigrations etc on pythonanywhere @Redfielder
- [x] set live on showcase and change team picture @Redfielder
- [x] remove password for pythonanywhere access @Redfielder
- [x] print, sign, and scan assessment sheet
- [x] Email with git/pythonAnywhere links to Leif (incl. assessment sheet and presentation) (email is already written) @Redfielder
- [x] Printed presentation with stapled declaration of originality form

**Comment by GeorgiosGoulos** [comment]
"Ensure new game is started with only 1 player (instead of what has been chosen in prev. session)"
It already does that...

**Comment by Redfielder** [comment]
First bullet point under urgent is the problem that causes this behaviour.  Agreed.

**Comment by RRothfeld** [comment]
## NEEDED FOR HAND-IN
- [x] set up pythonanywhere for being live (has to be refreshed) @Redfielder
- [x] Prepare presentation material (e.g. update ER, include checked list of included/omitted functions)
- [x] Make proper README for git (incl. how to install and set-up app, test user names/logins)
- [x] Include pip requirements file to git repo
- [x] Include population script

## OLD
- [x] Include testing @tvzeller @lmcphee89 @GeorgiosGoulos 
- [x] Css global stats page @Redfielder
- [x] Css session stats page @Redfielder
- [x] Show overall stats per answered statement at end-game-stats screen @GeorgiosGoulos 
- [x] Create Result instances from old sessions before they get deleted (after 1 hour inactivity) @lmcphee89 
- [x] design play options, and new statement pages @Redfielder
- [x] Ensure a new statement has at least one category
- [x] message when during a game, in options NO categories are being selected (site does not let you return to game, a note would be nice there)
- [x] Fix adding statement problem (doesn't work anymore)
- [x] Refurbish population script
- [x] Note for added player name changes
- [x] Gather pictures of us (either group or four single ones) @Redfielder
- [x] Write 1-2 pargraph(s) for About Us page @Redfielder
- [x] Limit nr. of players (must be between 1 and 5/6) @GeorgiosGoulos 
- [x] Add timer-symbol to index-page footer (synchronise with AJAX refresh of global counter) @Redfielder
- [x] Delete player numbers in options menu during play (at end, as it is used for testing)
- [x] Upon "End Game", close session (turn sessions, players, and answers into results; delete session players and answers afterwards; delete session cookie at user?) @lmcphee89 
- [x] Entered player names are only saved if Enter is pressed after entry (can we save it nonetheless, pressing enter is unintuitive, or maybe include an icon to save?) @tvzeller 
- [x] Refresh JS and CSS after AJAX in play screen @Redfield @tvzeller 
- [x] Linked to the above bulletpoint: if i have played a session with NSFW and start a new one, NSFW is enabled @GeorgiosGoulos 
- [x] Ensure new game is started with only 1 player (instead of what has been chosen in prev. session) @GeorgiosGoulos 
- [x] Toggle Button with player names
- [x] After answering, refresh form
- [x] Like statement button (+ changes in model)
- [x] use AJAX for updating the global session counters on the front page
- [x] store information in results model (has to be created, contains the following information; statement, gender, age, nationality, answer) before deleting answers, etc. when ending a session.
- [x] populate database with more statements
- [x] check time after last answered statement to close session after 24h --> use script on python anywhere (run once every day)
- [x] Include check if statement already answered within session (via list of answered statements in session model), and if no new statement end session
- [x] fix next-statement bug
- [x] Population Script @GeorgiosGoulos @Redfielder 
- [x] Gameplay Framework (no design) @GeorgiosGoulos 
- [x] Show statement (incl. only the selected categories) @GeorgiosGoulos 
- [x] Enter Answer per statement @tvzeller
- [x] Record Answer per statement @tvzeller
- [x] Add players @lmcphee89 
- [x] Add Statement Functionality @GeorgiosGoulos 
- [x] Front-End Development (HTML and CSS) @Redfielder 
- [x] end session screen statistics bring up information on what has been entered @GeorgiosGoulos 
- [x] add form to end session page to add info on players @lmcphee89
- [x] show statement category while playing @Redfielder 
- [x] overall stats page displays information for all answers @GeorgiosGoulos 
- [x] URL neverever.com/play?session=123 (is this readable?)  @GeorgiosGoulos
- [x] Session and player counter then delete old sessions, players, and answers!
- [x] Provide number of active session/players @Redfielder 
- [x] timestamps for all models (except categories) @Redfielder 
- [x] create player and session counter as new model ("globalcounters") @Redfielder 
- [x] after session: ask each player to provide age, gender, nationality (if they like) (maybe include on stast page) @GeorgiosGoulos
- [x] add answered_statements to session model (avoid statement repetition @Redfielder 
- [x] revert to NSFW boolean in statement instead of category @Redfielder 
- [x] FIRST question after sessions start should not be NSFW select categories @GeorgiosGoulos
- [x] enable player to input answer --> save answer in DB  @GeorgiosGoulos
- [x] Bootstrap buttons (design) @Redfielder 
- [x] look at stats page @Redfielder
